config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :users do
    resources :clients
  end

  resources :leads
  resources :not_interested
  resources :follow_ups

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :client

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :actions
  validates :address, uniqueness: true

  def fill_street
    "#{self.address} Oak Street, Traverse City, MI 02347"
  end

  def full_name
    self.first_name.capitalize + " " + self.last_name.capitalize
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :clients
  validates :email, uniqueness: true

  def full_name
    self.first_name.capitalize + " " + self.last_name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id].present?
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "You are signed in"
      redirect_to "/"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are signed out"
    redirect_to "/"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @user = current_user
    @clients = Client.all
  end

  def new
    @user = current_user
    @client = Client.new
  end

  def create
    @client = Client.new(client_params.merge(user_id: current_user.id))
    if @client.save
      flash[:notice] = "Client was successfully created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @client = Client.find(params[:id])
  end

  def update
    @user = current_user
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = "Client updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :phone_number,
    :address, :is_home, :is_interested, :user_id, :has_referral, :want_to_be_contacted, :notes)
  end
end

app/controllers/follow_ups_controller.rb
class FollowUpsController < ApplicationController
  def index
    @user = current_user
    @clients = @user.clients
  end

  def show
    @client = Client.find(params[:id])
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @user = current_user
    @clients = @user.clients.where(is_interested: true)
  end
end

app/controllers/not_interested_controller.rb
class NotInterestedController < ApplicationController
  def index
    @user = current_user
    @clients = @user.clients.where(is_interested: false)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :company))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "thanks for signing up"
      redirect_to "/"
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag sign_in_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Sign In" %>
<% end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= form_for [@user, @client], url: user_client_path(@user, @client) do |f| %>
<div class="form-group">
  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name %>
</div>
<div class="form-group">
  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div>
<div class="form-group">
  <%= f.label :phone_number, "Phone Number" %>
  <%= f.text_field :phone_number %>
</div>
<div class="form-group">
  <%= f.label :is_home, "Is Home" %>
  <%= f.check_box :is_home %>
</div>
<div class="form-group">
  <%= f.label :is_interested, "Is Interested" %>
  <%= f.check_box :is_interested %>
</div>
<div class="form-group">
  <%= f.label :has_referral, "Has Referral" %>
  <%= f.check_box :has_referral %>
</div>
<div class="form-group">
  <%= f.label :want_to_be_contacted, "Wants To Be Contacted" %>
  <%= f.check_box :want_to_be_contacted %>
</div>
<div class="form-group">
  <%= f.label :notes %>
  <%= f.text_area :notes %>
</div>
  <%= f.submit 'Edit Client', class: "btn btn-primary" %>
<% end %>

app/views/clients/index.html.erb
<h1>Listing Leads</h1>

<% @clients.where(is_interested: true).each do |client| %>
<table class="table">

  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Edit</th>
  </thead>

  <tbody>
    <tr>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.phone_number %></td>
      <td><%= client.address %></td>
      <td><%= link_to "Edit Client", edit_user_client_path(@user.id, client) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</br>

<% @clients.where(is_interested: false).each do |client| %>
<table class="table">

  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Edit</th>
  </thead>

  <tbody>
    <tr>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.phone_number %></td>
      <td><%= client.address %></td>
      <td><%= link_to "Edit Client", edit_user_client_path(@user.id, client) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create New Lead', new_user_client_path %>

app/views/clients/new.html.erb
<h1>Form For New Client</h1>

<%= form_for [@user, @client], url: user_clients_path do |f| %>
<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div>
<div class="form-group">
  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name %>
</div>
<div class="form-group">
  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div class="form-group">
  <%= f.label :phone_number, "Phone Number" %>
  <%= f.text_field :phone_number %>
</div>
<div class="form-group">
  <%= f.label :is_home, "Is Home" %>
  <%= f.check_box :is_home %>
</div>
<div class="form-group">
  <%= f.label :is_interested, "Is Interested" %>
  <%= f.check_box :is_interested %>
</div>
<div class="form-group">
  <%= f.label :has_referral, "Has Referral" %>
  <%= f.check_box :has_referral %>
</div>
<div class="form-group">
  <%= f.label :want_to_be_contacted, "Wants To Be Contacted" %>
  <%= f.check_box :want_to_be_contacted %>
</div>
<div class="form-group">
  <%= f.label :notes %>
  <%= f.text_area :notes %>
</div>
  <%= f.submit 'Add Client', class: "btn btn-primary" %>
<% end %>

app/views/follow_ups/index.html.erb
<div class="page-header">
  <h1><%= @user.full_name %>'s Action List</h1>
</div>

<table class="table">

  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Follow Up Actions</th>
    <th>Edit</th>
  </thead>

  <tbody>
    <tr>
    <% @clients.each do |client| %>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.phone_number %></td>
      <td><%= client.fill_street %></td>
      <td><%= link_to "Add Follow Up Action", new_follow_up_path %></td>
      <td><%= link_to "Edit Client", edit_user_client_path(@user.id, client) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/follow_ups/show.html.erb
<div class="page-header">
  <h1>Follow Up Actions for <%= @client.full_name %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AndyCrmApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Andy's CRM</a>
      </div>

      <% if current_user %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Leads <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% current_user.clients.each do |client| %>
              <li><%= link_to client.full_name, follow_up_path(client) %></li>
              <li class="divider"></li>
            <% end %>
          </ul>
        </li>
        <li></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.full_name, user_path(current_user) %></li>
          <li><%= link_to "Sign Out", sign_out_path %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign In", sign_in_path %></li>
          <li><%= link_to "Sign Up", sign_up_path %></li>
      </ul>
      <% end %>

    </div>
  </nav>

  <div class="container">

  <% if flash[:error] %>
    <% flash.each do | value | %>
      <div class="alert alert-danger", role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <% end %>

    <% if flash[:notice] %>
    <% flash.each do | value | %>
      <div class="alert alert-success", role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% end %>

  <%= yield %>

  <div class="page-header">
  </div>

  <footer>
    <div class="row">
      <div class="text-center">
        <%= link_to "Home", "/" %>
          |
        <%= link_to "About" %>
          |
        <%= link_to "Terms" %>
          |
        <%= link_to "FAQ" %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/leads/index.html.erb
<h1>Listing Leads</h1>

<% @clients.each do |client| %>
<table class="table">

  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Edit</th>
  </thead>

  <tbody>
    <tr>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.phone_number %></td>
      <td><%= client.fill_street %></td>
      <td><%= link_to "Edit Client", edit_user_client_path(@user.id, client) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</br>

<%= link_to 'Create New Lead', new_user_client_path(@user) %>

app/views/not_interested/index.html.erb
<h1>Not Interested</h1>

<table class="table">

  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Edit</th>
    <th>Notes</th>
  </thead>

  <tbody>
    <tr>
    <% @clients.each do |client| %>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.phone_number %></td>
      <td><%= client.address %></td>
      <td><%= link_to "Edit Client", edit_user_client_path(@user.id, client) %></td>
      <td><%= client.notes %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>Profile for <%= current_user.full_name %></h1>

app/views/welcome/index.html.erb
<h1>Welcome to Andy's CRM</h1>

<% unless current_user %>
  please sign in to view your portfolio
<% end %>

<% if current_user %>
  <%= link_to "Create New Lead", new_user_client_path(@user), class: "btn btn-primary" %>
  </br>
  <%= link_to "Leads", leads_path %>
  </br>
  <%= link_to "Follow Up", follow_ups_path %>
  </br>
  <%= link_to "Not Interested", not_interested_index_path %>
  </br>
<% end %>